// Code generated by protoc-gen-go. DO NOT EDIT.
// source: all.proto

/*
Package protobufs is a generated protocol buffer package.

It is generated from these files:
	all.proto

It has these top-level messages:
	ErrorResponse
	CreateSessionRequest
	CreateSessionResponse
	CreateCompanyRequest
	CreateCompanyResponse
	Studio
	CreateStudioRequest
	CreateStudioResponse
	DeleteStudioRequest
	DeleteStudioResponse
	Staff
	CreateStaffRequest
	CreateStaffResponse
	DeleteStaffRequest
	DeleteStaffResponse
	Card
	Customer
	CreateCustomerRequest
	CreateCustomerResponse
	DeleteCustomerRequest
	DeleteCustomerResponse
	SetCardOnCustomerRequest
	SetCardOnCustomerResponse
*/
package protobufs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ErrorType int32

const (
	ErrorType_INVALID_REQUEST_FORMAT ErrorType = 0
	ErrorType_NOT_FOUND              ErrorType = 1
	ErrorType_ALREADY_EXIST          ErrorType = 2
	ErrorType_INVALID_PASSWORD       ErrorType = 3
	ErrorType_INTERNAL_SERVER_ERROR  ErrorType = 4
	ErrorType_FORBIDDEN              ErrorType = 5
)

var ErrorType_name = map[int32]string{
	0: "INVALID_REQUEST_FORMAT",
	1: "NOT_FOUND",
	2: "ALREADY_EXIST",
	3: "INVALID_PASSWORD",
	4: "INTERNAL_SERVER_ERROR",
	5: "FORBIDDEN",
}
var ErrorType_value = map[string]int32{
	"INVALID_REQUEST_FORMAT": 0,
	"NOT_FOUND":              1,
	"ALREADY_EXIST":          2,
	"INVALID_PASSWORD":       3,
	"INTERNAL_SERVER_ERROR":  4,
	"FORBIDDEN":              5,
}

func (x ErrorType) String() string {
	return proto.EnumName(ErrorType_name, int32(x))
}
func (ErrorType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ErrorResponse struct {
	ErrorType ErrorType `protobuf:"varint,1,opt,name=errorType,enum=protobufs.ErrorType" json:"errorType,omitempty"`
	Message   string    `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *ErrorResponse) Reset()                    { *m = ErrorResponse{} }
func (m *ErrorResponse) String() string            { return proto.CompactTextString(m) }
func (*ErrorResponse) ProtoMessage()               {}
func (*ErrorResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ErrorResponse) GetErrorType() ErrorType {
	if m != nil {
		return m.ErrorType
	}
	return ErrorType_INVALID_REQUEST_FORMAT
}

func (m *ErrorResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type CreateSessionRequest struct {
	EmailAddress string `protobuf:"bytes,1,opt,name=emailAddress" json:"emailAddress,omitempty"`
	Password     string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *CreateSessionRequest) Reset()                    { *m = CreateSessionRequest{} }
func (m *CreateSessionRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateSessionRequest) ProtoMessage()               {}
func (*CreateSessionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateSessionRequest) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *CreateSessionRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateSessionResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *CreateSessionResponse) Reset()                    { *m = CreateSessionResponse{} }
func (m *CreateSessionResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateSessionResponse) ProtoMessage()               {}
func (*CreateSessionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateSessionResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type CreateCompanyRequest struct {
	Name         string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	EmailAddress string `protobuf:"bytes,2,opt,name=emailAddress" json:"emailAddress,omitempty"`
	Password     string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
}

func (m *CreateCompanyRequest) Reset()                    { *m = CreateCompanyRequest{} }
func (m *CreateCompanyRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateCompanyRequest) ProtoMessage()               {}
func (*CreateCompanyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CreateCompanyRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateCompanyRequest) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *CreateCompanyRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateCompanyResponse struct {
	Id           int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	EmailAddress string `protobuf:"bytes,3,opt,name=emailAddress" json:"emailAddress,omitempty"`
	CreatedAt    int64  `protobuf:"varint,4,opt,name=createdAt" json:"createdAt,omitempty"`
}

func (m *CreateCompanyResponse) Reset()                    { *m = CreateCompanyResponse{} }
func (m *CreateCompanyResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateCompanyResponse) ProtoMessage()               {}
func (*CreateCompanyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CreateCompanyResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreateCompanyResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateCompanyResponse) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *CreateCompanyResponse) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type Studio struct {
	Id        int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	CreatedAt int64  `protobuf:"varint,4,opt,name=createdAt" json:"createdAt,omitempty"`
}

func (m *Studio) Reset()                    { *m = Studio{} }
func (m *Studio) String() string            { return proto.CompactTextString(m) }
func (*Studio) ProtoMessage()               {}
func (*Studio) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Studio) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Studio) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Studio) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type CreateStudioRequest struct {
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *CreateStudioRequest) Reset()                    { *m = CreateStudioRequest{} }
func (m *CreateStudioRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateStudioRequest) ProtoMessage()               {}
func (*CreateStudioRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CreateStudioRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateStudioResponse struct {
	Studio *Studio `protobuf:"bytes,1,opt,name=studio" json:"studio,omitempty"`
}

func (m *CreateStudioResponse) Reset()                    { *m = CreateStudioResponse{} }
func (m *CreateStudioResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateStudioResponse) ProtoMessage()               {}
func (*CreateStudioResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *CreateStudioResponse) GetStudio() *Studio {
	if m != nil {
		return m.Studio
	}
	return nil
}

type DeleteStudioRequest struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteStudioRequest) Reset()                    { *m = DeleteStudioRequest{} }
func (m *DeleteStudioRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteStudioRequest) ProtoMessage()               {}
func (*DeleteStudioRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *DeleteStudioRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteStudioResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *DeleteStudioResponse) Reset()                    { *m = DeleteStudioResponse{} }
func (m *DeleteStudioResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteStudioResponse) ProtoMessage()               {}
func (*DeleteStudioResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *DeleteStudioResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type Staff struct {
	Id        int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	CreatedAt int64  `protobuf:"varint,4,opt,name=createdAt" json:"createdAt,omitempty"`
}

func (m *Staff) Reset()                    { *m = Staff{} }
func (m *Staff) String() string            { return proto.CompactTextString(m) }
func (*Staff) ProtoMessage()               {}
func (*Staff) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Staff) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Staff) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Staff) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type CreateStaffRequest struct {
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *CreateStaffRequest) Reset()                    { *m = CreateStaffRequest{} }
func (m *CreateStaffRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateStaffRequest) ProtoMessage()               {}
func (*CreateStaffRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *CreateStaffRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateStaffResponse struct {
	Staff *Staff `protobuf:"bytes,1,opt,name=staff" json:"staff,omitempty"`
}

func (m *CreateStaffResponse) Reset()                    { *m = CreateStaffResponse{} }
func (m *CreateStaffResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateStaffResponse) ProtoMessage()               {}
func (*CreateStaffResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *CreateStaffResponse) GetStaff() *Staff {
	if m != nil {
		return m.Staff
	}
	return nil
}

type DeleteStaffRequest struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteStaffRequest) Reset()                    { *m = DeleteStaffRequest{} }
func (m *DeleteStaffRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteStaffRequest) ProtoMessage()               {}
func (*DeleteStaffRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *DeleteStaffRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteStaffResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *DeleteStaffResponse) Reset()                    { *m = DeleteStaffResponse{} }
func (m *DeleteStaffResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteStaffResponse) ProtoMessage()               {}
func (*DeleteStaffResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *DeleteStaffResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type Card struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Credit int32  `protobuf:"varint,2,opt,name=credit" json:"credit,omitempty"`
}

func (m *Card) Reset()                    { *m = Card{} }
func (m *Card) String() string            { return proto.CompactTextString(m) }
func (*Card) ProtoMessage()               {}
func (*Card) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *Card) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Card) GetCredit() int32 {
	if m != nil {
		return m.Credit
	}
	return 0
}

type Customer struct {
	Id          int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Card        *Card  `protobuf:"bytes,4,opt,name=card" json:"card,omitempty"`
}

func (m *Customer) Reset()                    { *m = Customer{} }
func (m *Customer) String() string            { return proto.CompactTextString(m) }
func (*Customer) ProtoMessage()               {}
func (*Customer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *Customer) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Customer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Customer) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Customer) GetCard() *Card {
	if m != nil {
		return m.Card
	}
	return nil
}

type CreateCustomerRequest struct {
	Name        string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Card        *Card  `protobuf:"bytes,3,opt,name=card" json:"card,omitempty"`
}

func (m *CreateCustomerRequest) Reset()                    { *m = CreateCustomerRequest{} }
func (m *CreateCustomerRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateCustomerRequest) ProtoMessage()               {}
func (*CreateCustomerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *CreateCustomerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateCustomerRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateCustomerRequest) GetCard() *Card {
	if m != nil {
		return m.Card
	}
	return nil
}

type CreateCustomerResponse struct {
	Customer *Customer `protobuf:"bytes,1,opt,name=customer" json:"customer,omitempty"`
}

func (m *CreateCustomerResponse) Reset()                    { *m = CreateCustomerResponse{} }
func (m *CreateCustomerResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateCustomerResponse) ProtoMessage()               {}
func (*CreateCustomerResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *CreateCustomerResponse) GetCustomer() *Customer {
	if m != nil {
		return m.Customer
	}
	return nil
}

type DeleteCustomerRequest struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteCustomerRequest) Reset()                    { *m = DeleteCustomerRequest{} }
func (m *DeleteCustomerRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteCustomerRequest) ProtoMessage()               {}
func (*DeleteCustomerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *DeleteCustomerRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteCustomerResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *DeleteCustomerResponse) Reset()                    { *m = DeleteCustomerResponse{} }
func (m *DeleteCustomerResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteCustomerResponse) ProtoMessage()               {}
func (*DeleteCustomerResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *DeleteCustomerResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type SetCardOnCustomerRequest struct {
	CustomerId int32 `protobuf:"varint,1,opt,name=customerId" json:"customerId,omitempty"`
	Card       *Card `protobuf:"bytes,2,opt,name=card" json:"card,omitempty"`
}

func (m *SetCardOnCustomerRequest) Reset()                    { *m = SetCardOnCustomerRequest{} }
func (m *SetCardOnCustomerRequest) String() string            { return proto.CompactTextString(m) }
func (*SetCardOnCustomerRequest) ProtoMessage()               {}
func (*SetCardOnCustomerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *SetCardOnCustomerRequest) GetCustomerId() int32 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

func (m *SetCardOnCustomerRequest) GetCard() *Card {
	if m != nil {
		return m.Card
	}
	return nil
}

type SetCardOnCustomerResponse struct {
	Customer *Customer `protobuf:"bytes,1,opt,name=customer" json:"customer,omitempty"`
}

func (m *SetCardOnCustomerResponse) Reset()                    { *m = SetCardOnCustomerResponse{} }
func (m *SetCardOnCustomerResponse) String() string            { return proto.CompactTextString(m) }
func (*SetCardOnCustomerResponse) ProtoMessage()               {}
func (*SetCardOnCustomerResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *SetCardOnCustomerResponse) GetCustomer() *Customer {
	if m != nil {
		return m.Customer
	}
	return nil
}

func init() {
	proto.RegisterType((*ErrorResponse)(nil), "protobufs.ErrorResponse")
	proto.RegisterType((*CreateSessionRequest)(nil), "protobufs.CreateSessionRequest")
	proto.RegisterType((*CreateSessionResponse)(nil), "protobufs.CreateSessionResponse")
	proto.RegisterType((*CreateCompanyRequest)(nil), "protobufs.CreateCompanyRequest")
	proto.RegisterType((*CreateCompanyResponse)(nil), "protobufs.CreateCompanyResponse")
	proto.RegisterType((*Studio)(nil), "protobufs.Studio")
	proto.RegisterType((*CreateStudioRequest)(nil), "protobufs.CreateStudioRequest")
	proto.RegisterType((*CreateStudioResponse)(nil), "protobufs.CreateStudioResponse")
	proto.RegisterType((*DeleteStudioRequest)(nil), "protobufs.DeleteStudioRequest")
	proto.RegisterType((*DeleteStudioResponse)(nil), "protobufs.DeleteStudioResponse")
	proto.RegisterType((*Staff)(nil), "protobufs.Staff")
	proto.RegisterType((*CreateStaffRequest)(nil), "protobufs.CreateStaffRequest")
	proto.RegisterType((*CreateStaffResponse)(nil), "protobufs.CreateStaffResponse")
	proto.RegisterType((*DeleteStaffRequest)(nil), "protobufs.DeleteStaffRequest")
	proto.RegisterType((*DeleteStaffResponse)(nil), "protobufs.DeleteStaffResponse")
	proto.RegisterType((*Card)(nil), "protobufs.Card")
	proto.RegisterType((*Customer)(nil), "protobufs.Customer")
	proto.RegisterType((*CreateCustomerRequest)(nil), "protobufs.CreateCustomerRequest")
	proto.RegisterType((*CreateCustomerResponse)(nil), "protobufs.CreateCustomerResponse")
	proto.RegisterType((*DeleteCustomerRequest)(nil), "protobufs.DeleteCustomerRequest")
	proto.RegisterType((*DeleteCustomerResponse)(nil), "protobufs.DeleteCustomerResponse")
	proto.RegisterType((*SetCardOnCustomerRequest)(nil), "protobufs.SetCardOnCustomerRequest")
	proto.RegisterType((*SetCardOnCustomerResponse)(nil), "protobufs.SetCardOnCustomerResponse")
	proto.RegisterEnum("protobufs.ErrorType", ErrorType_name, ErrorType_value)
}

func init() { proto.RegisterFile("all.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 654 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0xa5, 0xe9, 0xc7, 0x9a, 0x3b, 0x36, 0x32, 0xaf, 0xab, 0xba, 0x09, 0xa1, 0xca, 0x7c, 0x75,
	0x3c, 0x74, 0x50, 0x9e, 0x79, 0x08, 0x4d, 0x26, 0x05, 0x95, 0x16, 0x9c, 0x6e, 0xc0, 0x03, 0xaa,
	0xb2, 0xc4, 0x45, 0x41, 0x6d, 0x53, 0xec, 0x54, 0x68, 0x0f, 0xfc, 0x00, 0xfe, 0x35, 0x8a, 0x67,
	0xa7, 0x59, 0xd8, 0xd2, 0x09, 0xf1, 0xd4, 0xde, 0xeb, 0xd3, 0x73, 0xce, 0x3d, 0xd7, 0x56, 0x41,
	0xf7, 0x66, 0xb3, 0xee, 0x92, 0x45, 0x71, 0x84, 0x74, 0xf1, 0x71, 0xb1, 0x9a, 0x72, 0xfc, 0x15,
	0x76, 0x6c, 0xc6, 0x22, 0x46, 0x28, 0x5f, 0x46, 0x0b, 0x4e, 0x51, 0x0f, 0x74, 0x9a, 0x34, 0xc6,
	0x97, 0x4b, 0xda, 0x2a, 0xb5, 0x4b, 0x9d, 0xdd, 0x5e, 0xa3, 0x9b, 0xe2, 0xbb, 0xb6, 0x3a, 0x23,
	0x6b, 0x18, 0x6a, 0xc1, 0xd6, 0x9c, 0x72, 0xee, 0x7d, 0xa3, 0x2d, 0xad, 0x5d, 0xea, 0xe8, 0x44,
	0x95, 0xf8, 0x1c, 0x1a, 0x7d, 0x46, 0xbd, 0x98, 0xba, 0x94, 0xf3, 0x30, 0x5a, 0x10, 0xfa, 0x63,
	0x45, 0x79, 0x8c, 0x30, 0xdc, 0xa7, 0x73, 0x2f, 0x9c, 0x99, 0x41, 0xc0, 0x28, 0xe7, 0x42, 0x48,
	0x27, 0xd7, 0x7a, 0xe8, 0x08, 0xea, 0x4b, 0x8f, 0xf3, 0x9f, 0x11, 0x0b, 0x24, 0x6d, 0x5a, 0xe3,
	0x57, 0x70, 0x90, 0xe3, 0x95, 0xf6, 0x5b, 0xb0, 0xc5, 0x57, 0xbe, 0xaf, 0x38, 0xeb, 0x44, 0x95,
	0xf8, 0xbb, 0xb2, 0xd2, 0x8f, 0xe6, 0x4b, 0x6f, 0x71, 0xa9, 0xac, 0x20, 0xa8, 0x2c, 0xbc, 0x39,
	0x95, 0x16, 0xc4, 0xf7, 0xbf, 0xec, 0x69, 0x1b, 0xec, 0x95, 0x73, 0xf6, 0x7e, 0x29, 0x7b, 0xa9,
	0x96, 0xb4, 0xb7, 0x0b, 0x5a, 0x18, 0x08, 0xa9, 0x2a, 0xd1, 0xc2, 0x20, 0x15, 0xd7, 0x0a, 0xc4,
	0xcb, 0x37, 0x88, 0x3f, 0x04, 0xdd, 0x17, 0x02, 0x81, 0x19, 0xb7, 0x2a, 0xed, 0x52, 0xa7, 0x4c,
	0xd6, 0x0d, 0xfc, 0x0e, 0x6a, 0x6e, 0xbc, 0x0a, 0xc2, 0xe8, 0x4e, 0x7a, 0xc5, 0x5c, 0xc7, 0xb0,
	0x2f, 0x93, 0x16, 0x8c, 0xf9, 0xd4, 0x32, 0x44, 0xd8, 0x4c, 0x97, 0x2d, 0xa1, 0x72, 0xe8, 0x63,
	0xa8, 0x71, 0xd1, 0x11, 0x46, 0xb6, 0x7b, 0x7b, 0x99, 0xfb, 0x24, 0xa1, 0x12, 0x80, 0x9f, 0xc2,
	0xbe, 0x45, 0x67, 0x34, 0xaf, 0x96, 0x1b, 0x03, 0xbf, 0x84, 0xc6, 0x75, 0xd8, 0xc6, 0xed, 0x3b,
	0x50, 0x75, 0x63, 0x6f, 0x3a, 0xfd, 0x0f, 0x89, 0x74, 0x00, 0xa9, 0x31, 0xbd, 0xe9, 0xb4, 0x28,
	0x90, 0x37, 0xeb, 0xec, 0x04, 0x52, 0xba, 0x7c, 0x06, 0x55, 0x9e, 0x34, 0x64, 0x1c, 0xc6, 0xb5,
	0x38, 0x12, 0xe0, 0xd5, 0x31, 0x7e, 0x02, 0x48, 0x4d, 0x99, 0x11, 0xca, 0x67, 0x71, 0xb2, 0x8e,
	0x2c, 0x2b, 0x72, 0x7b, 0x14, 0x5d, 0xa8, 0xf4, 0x3d, 0x16, 0x64, 0x88, 0x74, 0x91, 0x44, 0x13,
	0x6a, 0x3e, 0xa3, 0x41, 0x18, 0x8b, 0x19, 0xaa, 0x44, 0x56, 0x78, 0x05, 0xf5, 0xfe, 0x8a, 0xc7,
	0xd1, 0x9c, 0xb2, 0x3b, 0xa5, 0xd7, 0x86, 0xed, 0x80, 0x72, 0x9f, 0x85, 0xcb, 0x38, 0x8c, 0x16,
	0xf2, 0xfa, 0x66, 0x5b, 0xe8, 0x31, 0x54, 0x7c, 0x8f, 0x05, 0x22, 0xda, 0xed, 0xde, 0x83, 0xcc,
	0xfc, 0x89, 0x31, 0x22, 0x0e, 0x31, 0x4b, 0xdf, 0x90, 0x14, 0x2f, 0x7a, 0xb0, 0x39, 0x4d, 0xed,
	0x76, 0xcd, 0x72, 0x91, 0xa6, 0x03, 0xcd, 0xbc, 0xa6, 0x8c, 0xf3, 0x04, 0xea, 0xbe, 0xec, 0xc9,
	0xb5, 0xed, 0x67, 0x29, 0x14, 0x3c, 0x05, 0xe1, 0xe7, 0x70, 0x70, 0xb5, 0x96, 0xbc, 0xfd, 0xfc,
	0xfe, 0x7a, 0xd0, 0xcc, 0x03, 0x37, 0xae, 0x70, 0x02, 0x2d, 0x97, 0xc6, 0x89, 0xf1, 0xd1, 0x22,
	0xcf, 0xff, 0x08, 0x40, 0x99, 0x70, 0x94, 0x4e, 0xa6, 0x93, 0x06, 0xa1, 0x15, 0x05, 0x31, 0x80,
	0xc3, 0x1b, 0x04, 0xfe, 0x31, 0x8b, 0x17, 0xbf, 0x4b, 0xa0, 0xa7, 0x7f, 0x1c, 0xe8, 0x08, 0x9a,
	0xce, 0xf0, 0xdc, 0x1c, 0x38, 0xd6, 0x84, 0xd8, 0x1f, 0xcf, 0x6c, 0x77, 0x3c, 0x39, 0x1d, 0x91,
	0xf7, 0xe6, 0xd8, 0xb8, 0x87, 0x76, 0x40, 0x1f, 0x8e, 0x92, 0xfa, 0x6c, 0x68, 0x19, 0x25, 0xb4,
	0x07, 0x3b, 0xe6, 0x80, 0xd8, 0xa6, 0xf5, 0x65, 0x62, 0x7f, 0x76, 0xdc, 0xb1, 0xa1, 0xa1, 0x06,
	0x18, 0xea, 0xd7, 0x1f, 0x4c, 0xd7, 0xfd, 0x34, 0x22, 0x96, 0x51, 0x46, 0x87, 0x70, 0xe0, 0x0c,
	0xc7, 0x36, 0x19, 0x9a, 0x83, 0x89, 0x6b, 0x93, 0x73, 0x9b, 0x4c, 0x6c, 0x42, 0x46, 0xc4, 0xa8,
	0x24, 0x94, 0xa7, 0x23, 0xf2, 0xd6, 0xb1, 0x2c, 0x7b, 0x68, 0x54, 0x2f, 0x6a, 0xc2, 0xe9, 0xeb,
	0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc2, 0x8f, 0x66, 0x7d, 0x0f, 0x07, 0x00, 0x00,
}
