// Code generated by protoc-gen-go. DO NOT EDIT.
// source: all.proto

/*
Package protobufs is a generated protocol buffer package.

It is generated from these files:
	all.proto

It has these top-level messages:
	ErrorResponse
	Company
	CreateSessionRequest
	CreateSessionResponse
	CreateCompanyRequest
	CreateCompanyResponse
	SetCompanyImageLinkRequest
	SetCompanyImageLinkResponse
	SetCompanyPasswordRequest
	SetCompanyPasswordResponse
	Studio
	SelectStudiosResponse
	CreateStudioRequest
	CreateStudioResponse
	UpdateStudioRequest
	UpdateStudioResponse
	DeleteStudioRequest
	DeleteStudioResponse
	Staff
	SelectStaffsResponse
	CreateStaffRequest
	CreateStaffResponse
	DeleteStaffRequest
	DeleteStaffResponse
	UpdateStaffRequest
	UpdateStaffResponse
	Card
	Customer
	SelectCustomersResponse
	CreateCustomerRequest
	CreateCustomerResponse
	DeleteCustomerRequest
	DeleteCustomerResponse
	SetCardOnCustomerRequest
	SetCardOnCustomerResponse
*/
package protobufs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ErrorType int32

const (
	ErrorType_INVALID_REQUEST_FORMAT ErrorType = 0
	ErrorType_NOT_FOUND              ErrorType = 1
	ErrorType_ALREADY_EXIST          ErrorType = 2
	ErrorType_INVALID_PASSWORD       ErrorType = 3
	ErrorType_INTERNAL_SERVER_ERROR  ErrorType = 4
	ErrorType_FORBIDDEN              ErrorType = 5
	ErrorType_CONFLICT               ErrorType = 6
)

var ErrorType_name = map[int32]string{
	0: "INVALID_REQUEST_FORMAT",
	1: "NOT_FOUND",
	2: "ALREADY_EXIST",
	3: "INVALID_PASSWORD",
	4: "INTERNAL_SERVER_ERROR",
	5: "FORBIDDEN",
	6: "CONFLICT",
}
var ErrorType_value = map[string]int32{
	"INVALID_REQUEST_FORMAT": 0,
	"NOT_FOUND":              1,
	"ALREADY_EXIST":          2,
	"INVALID_PASSWORD":       3,
	"INTERNAL_SERVER_ERROR":  4,
	"FORBIDDEN":              5,
	"CONFLICT":               6,
}

func (x ErrorType) String() string {
	return proto.EnumName(ErrorType_name, int32(x))
}
func (ErrorType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ErrorResponse struct {
	ErrorType ErrorType `protobuf:"varint,1,opt,name=errorType,enum=protobufs.ErrorType" json:"errorType,omitempty"`
	Message   string    `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *ErrorResponse) Reset()                    { *m = ErrorResponse{} }
func (m *ErrorResponse) String() string            { return proto.CompactTextString(m) }
func (*ErrorResponse) ProtoMessage()               {}
func (*ErrorResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ErrorResponse) GetErrorType() ErrorType {
	if m != nil {
		return m.ErrorType
	}
	return ErrorType_INVALID_REQUEST_FORMAT
}

func (m *ErrorResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Company struct {
	Id           int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	EmailAddress string `protobuf:"bytes,3,opt,name=emailAddress" json:"emailAddress,omitempty"`
	CreatedAt    int64  `protobuf:"varint,4,opt,name=createdAt" json:"createdAt,omitempty"`
	ImageLInk    string `protobuf:"bytes,5,opt,name=imageLInk" json:"imageLInk,omitempty"`
}

func (m *Company) Reset()                    { *m = Company{} }
func (m *Company) String() string            { return proto.CompactTextString(m) }
func (*Company) ProtoMessage()               {}
func (*Company) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Company) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Company) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Company) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *Company) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Company) GetImageLInk() string {
	if m != nil {
		return m.ImageLInk
	}
	return ""
}

type CreateSessionRequest struct {
	EmailAddress string `protobuf:"bytes,1,opt,name=emailAddress" json:"emailAddress,omitempty"`
	Password     string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *CreateSessionRequest) Reset()                    { *m = CreateSessionRequest{} }
func (m *CreateSessionRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateSessionRequest) ProtoMessage()               {}
func (*CreateSessionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateSessionRequest) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *CreateSessionRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateSessionResponse struct {
	Company *Company `protobuf:"bytes,1,opt,name=company" json:"company,omitempty"`
}

func (m *CreateSessionResponse) Reset()                    { *m = CreateSessionResponse{} }
func (m *CreateSessionResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateSessionResponse) ProtoMessage()               {}
func (*CreateSessionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CreateSessionResponse) GetCompany() *Company {
	if m != nil {
		return m.Company
	}
	return nil
}

type CreateCompanyRequest struct {
	Name         string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	EmailAddress string `protobuf:"bytes,2,opt,name=emailAddress" json:"emailAddress,omitempty"`
	Password     string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
}

func (m *CreateCompanyRequest) Reset()                    { *m = CreateCompanyRequest{} }
func (m *CreateCompanyRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateCompanyRequest) ProtoMessage()               {}
func (*CreateCompanyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CreateCompanyRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateCompanyRequest) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *CreateCompanyRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateCompanyResponse struct {
	Company *Company `protobuf:"bytes,1,opt,name=company" json:"company,omitempty"`
}

func (m *CreateCompanyResponse) Reset()                    { *m = CreateCompanyResponse{} }
func (m *CreateCompanyResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateCompanyResponse) ProtoMessage()               {}
func (*CreateCompanyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CreateCompanyResponse) GetCompany() *Company {
	if m != nil {
		return m.Company
	}
	return nil
}

type SetCompanyImageLinkRequest struct {
	ImageLink string `protobuf:"bytes,1,opt,name=imageLink" json:"imageLink,omitempty"`
}

func (m *SetCompanyImageLinkRequest) Reset()                    { *m = SetCompanyImageLinkRequest{} }
func (m *SetCompanyImageLinkRequest) String() string            { return proto.CompactTextString(m) }
func (*SetCompanyImageLinkRequest) ProtoMessage()               {}
func (*SetCompanyImageLinkRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *SetCompanyImageLinkRequest) GetImageLink() string {
	if m != nil {
		return m.ImageLink
	}
	return ""
}

type SetCompanyImageLinkResponse struct {
	Company *Company `protobuf:"bytes,1,opt,name=company" json:"company,omitempty"`
}

func (m *SetCompanyImageLinkResponse) Reset()                    { *m = SetCompanyImageLinkResponse{} }
func (m *SetCompanyImageLinkResponse) String() string            { return proto.CompactTextString(m) }
func (*SetCompanyImageLinkResponse) ProtoMessage()               {}
func (*SetCompanyImageLinkResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *SetCompanyImageLinkResponse) GetCompany() *Company {
	if m != nil {
		return m.Company
	}
	return nil
}

type SetCompanyPasswordRequest struct {
	Password string `protobuf:"bytes,1,opt,name=password" json:"password,omitempty"`
}

func (m *SetCompanyPasswordRequest) Reset()                    { *m = SetCompanyPasswordRequest{} }
func (m *SetCompanyPasswordRequest) String() string            { return proto.CompactTextString(m) }
func (*SetCompanyPasswordRequest) ProtoMessage()               {}
func (*SetCompanyPasswordRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *SetCompanyPasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SetCompanyPasswordResponse struct {
	Company *Company `protobuf:"bytes,1,opt,name=company" json:"company,omitempty"`
}

func (m *SetCompanyPasswordResponse) Reset()                    { *m = SetCompanyPasswordResponse{} }
func (m *SetCompanyPasswordResponse) String() string            { return proto.CompactTextString(m) }
func (*SetCompanyPasswordResponse) ProtoMessage()               {}
func (*SetCompanyPasswordResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *SetCompanyPasswordResponse) GetCompany() *Company {
	if m != nil {
		return m.Company
	}
	return nil
}

type Studio struct {
	Id          int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Address     string `protobuf:"bytes,3,opt,name=address" json:"address,omitempty"`
	PhoneNumber string `protobuf:"bytes,4,opt,name=phoneNumber" json:"phoneNumber,omitempty"`
	CreatedAt   int64  `protobuf:"varint,5,opt,name=createdAt" json:"createdAt,omitempty"`
	ImageLink   string `protobuf:"bytes,6,opt,name=imageLink" json:"imageLink,omitempty"`
}

func (m *Studio) Reset()                    { *m = Studio{} }
func (m *Studio) String() string            { return proto.CompactTextString(m) }
func (*Studio) ProtoMessage()               {}
func (*Studio) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Studio) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Studio) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Studio) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Studio) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *Studio) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Studio) GetImageLink() string {
	if m != nil {
		return m.ImageLink
	}
	return ""
}

type SelectStudiosResponse struct {
	Studios []*Studio `protobuf:"bytes,1,rep,name=studios" json:"studios,omitempty"`
}

func (m *SelectStudiosResponse) Reset()                    { *m = SelectStudiosResponse{} }
func (m *SelectStudiosResponse) String() string            { return proto.CompactTextString(m) }
func (*SelectStudiosResponse) ProtoMessage()               {}
func (*SelectStudiosResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *SelectStudiosResponse) GetStudios() []*Studio {
	if m != nil {
		return m.Studios
	}
	return nil
}

type CreateStudioRequest struct {
	Name        string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Address     string `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
	PhoneNumber string `protobuf:"bytes,3,opt,name=phoneNumber" json:"phoneNumber,omitempty"`
	ImageLink   string `protobuf:"bytes,4,opt,name=imageLink" json:"imageLink,omitempty"`
}

func (m *CreateStudioRequest) Reset()                    { *m = CreateStudioRequest{} }
func (m *CreateStudioRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateStudioRequest) ProtoMessage()               {}
func (*CreateStudioRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *CreateStudioRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateStudioRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *CreateStudioRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *CreateStudioRequest) GetImageLink() string {
	if m != nil {
		return m.ImageLink
	}
	return ""
}

type CreateStudioResponse struct {
	Studio *Studio `protobuf:"bytes,1,opt,name=studio" json:"studio,omitempty"`
}

func (m *CreateStudioResponse) Reset()                    { *m = CreateStudioResponse{} }
func (m *CreateStudioResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateStudioResponse) ProtoMessage()               {}
func (*CreateStudioResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *CreateStudioResponse) GetStudio() *Studio {
	if m != nil {
		return m.Studio
	}
	return nil
}

type UpdateStudioRequest struct {
	Studio *Studio `protobuf:"bytes,1,opt,name=studio" json:"studio,omitempty"`
}

func (m *UpdateStudioRequest) Reset()                    { *m = UpdateStudioRequest{} }
func (m *UpdateStudioRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateStudioRequest) ProtoMessage()               {}
func (*UpdateStudioRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *UpdateStudioRequest) GetStudio() *Studio {
	if m != nil {
		return m.Studio
	}
	return nil
}

type UpdateStudioResponse struct {
	Studio *Studio `protobuf:"bytes,1,opt,name=studio" json:"studio,omitempty"`
}

func (m *UpdateStudioResponse) Reset()                    { *m = UpdateStudioResponse{} }
func (m *UpdateStudioResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateStudioResponse) ProtoMessage()               {}
func (*UpdateStudioResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *UpdateStudioResponse) GetStudio() *Studio {
	if m != nil {
		return m.Studio
	}
	return nil
}

type DeleteStudioRequest struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteStudioRequest) Reset()                    { *m = DeleteStudioRequest{} }
func (m *DeleteStudioRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteStudioRequest) ProtoMessage()               {}
func (*DeleteStudioRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *DeleteStudioRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteStudioResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *DeleteStudioResponse) Reset()                    { *m = DeleteStudioResponse{} }
func (m *DeleteStudioResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteStudioResponse) ProtoMessage()               {}
func (*DeleteStudioResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *DeleteStudioResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type Staff struct {
	Id        int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	CreatedAt int64  `protobuf:"varint,3,opt,name=createdAt" json:"createdAt,omitempty"`
	ImageLink string `protobuf:"bytes,4,opt,name=imageLink" json:"imageLink,omitempty"`
}

func (m *Staff) Reset()                    { *m = Staff{} }
func (m *Staff) String() string            { return proto.CompactTextString(m) }
func (*Staff) ProtoMessage()               {}
func (*Staff) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *Staff) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Staff) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Staff) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Staff) GetImageLink() string {
	if m != nil {
		return m.ImageLink
	}
	return ""
}

type SelectStaffsResponse struct {
	Staffs []*Staff `protobuf:"bytes,1,rep,name=staffs" json:"staffs,omitempty"`
}

func (m *SelectStaffsResponse) Reset()                    { *m = SelectStaffsResponse{} }
func (m *SelectStaffsResponse) String() string            { return proto.CompactTextString(m) }
func (*SelectStaffsResponse) ProtoMessage()               {}
func (*SelectStaffsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *SelectStaffsResponse) GetStaffs() []*Staff {
	if m != nil {
		return m.Staffs
	}
	return nil
}

type CreateStaffRequest struct {
	Name      string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	ImageLink string `protobuf:"bytes,2,opt,name=imageLink" json:"imageLink,omitempty"`
}

func (m *CreateStaffRequest) Reset()                    { *m = CreateStaffRequest{} }
func (m *CreateStaffRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateStaffRequest) ProtoMessage()               {}
func (*CreateStaffRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *CreateStaffRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateStaffRequest) GetImageLink() string {
	if m != nil {
		return m.ImageLink
	}
	return ""
}

type CreateStaffResponse struct {
	Staff *Staff `protobuf:"bytes,1,opt,name=staff" json:"staff,omitempty"`
}

func (m *CreateStaffResponse) Reset()                    { *m = CreateStaffResponse{} }
func (m *CreateStaffResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateStaffResponse) ProtoMessage()               {}
func (*CreateStaffResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *CreateStaffResponse) GetStaff() *Staff {
	if m != nil {
		return m.Staff
	}
	return nil
}

type DeleteStaffRequest struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteStaffRequest) Reset()                    { *m = DeleteStaffRequest{} }
func (m *DeleteStaffRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteStaffRequest) ProtoMessage()               {}
func (*DeleteStaffRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *DeleteStaffRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteStaffResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *DeleteStaffResponse) Reset()                    { *m = DeleteStaffResponse{} }
func (m *DeleteStaffResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteStaffResponse) ProtoMessage()               {}
func (*DeleteStaffResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *DeleteStaffResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type UpdateStaffRequest struct {
	Staff *Staff `protobuf:"bytes,1,opt,name=staff" json:"staff,omitempty"`
}

func (m *UpdateStaffRequest) Reset()                    { *m = UpdateStaffRequest{} }
func (m *UpdateStaffRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateStaffRequest) ProtoMessage()               {}
func (*UpdateStaffRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *UpdateStaffRequest) GetStaff() *Staff {
	if m != nil {
		return m.Staff
	}
	return nil
}

type UpdateStaffResponse struct {
	Staff *Staff `protobuf:"bytes,1,opt,name=staff" json:"staff,omitempty"`
}

func (m *UpdateStaffResponse) Reset()                    { *m = UpdateStaffResponse{} }
func (m *UpdateStaffResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateStaffResponse) ProtoMessage()               {}
func (*UpdateStaffResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *UpdateStaffResponse) GetStaff() *Staff {
	if m != nil {
		return m.Staff
	}
	return nil
}

type Card struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Credit int32  `protobuf:"varint,2,opt,name=credit" json:"credit,omitempty"`
}

func (m *Card) Reset()                    { *m = Card{} }
func (m *Card) String() string            { return proto.CompactTextString(m) }
func (*Card) ProtoMessage()               {}
func (*Card) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *Card) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Card) GetCredit() int32 {
	if m != nil {
		return m.Credit
	}
	return 0
}

type Customer struct {
	Id          int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Card        *Card  `protobuf:"bytes,4,opt,name=card" json:"card,omitempty"`
}

func (m *Customer) Reset()                    { *m = Customer{} }
func (m *Customer) String() string            { return proto.CompactTextString(m) }
func (*Customer) ProtoMessage()               {}
func (*Customer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *Customer) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Customer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Customer) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Customer) GetCard() *Card {
	if m != nil {
		return m.Card
	}
	return nil
}

type SelectCustomersResponse struct {
	Customers []*Customer `protobuf:"bytes,1,rep,name=customers" json:"customers,omitempty"`
}

func (m *SelectCustomersResponse) Reset()                    { *m = SelectCustomersResponse{} }
func (m *SelectCustomersResponse) String() string            { return proto.CompactTextString(m) }
func (*SelectCustomersResponse) ProtoMessage()               {}
func (*SelectCustomersResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *SelectCustomersResponse) GetCustomers() []*Customer {
	if m != nil {
		return m.Customers
	}
	return nil
}

type CreateCustomerRequest struct {
	Name        string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Card        *Card  `protobuf:"bytes,3,opt,name=card" json:"card,omitempty"`
}

func (m *CreateCustomerRequest) Reset()                    { *m = CreateCustomerRequest{} }
func (m *CreateCustomerRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateCustomerRequest) ProtoMessage()               {}
func (*CreateCustomerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *CreateCustomerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateCustomerRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateCustomerRequest) GetCard() *Card {
	if m != nil {
		return m.Card
	}
	return nil
}

type CreateCustomerResponse struct {
	Customer *Customer `protobuf:"bytes,1,opt,name=customer" json:"customer,omitempty"`
}

func (m *CreateCustomerResponse) Reset()                    { *m = CreateCustomerResponse{} }
func (m *CreateCustomerResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateCustomerResponse) ProtoMessage()               {}
func (*CreateCustomerResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *CreateCustomerResponse) GetCustomer() *Customer {
	if m != nil {
		return m.Customer
	}
	return nil
}

type DeleteCustomerRequest struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteCustomerRequest) Reset()                    { *m = DeleteCustomerRequest{} }
func (m *DeleteCustomerRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteCustomerRequest) ProtoMessage()               {}
func (*DeleteCustomerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *DeleteCustomerRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteCustomerResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *DeleteCustomerResponse) Reset()                    { *m = DeleteCustomerResponse{} }
func (m *DeleteCustomerResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteCustomerResponse) ProtoMessage()               {}
func (*DeleteCustomerResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

func (m *DeleteCustomerResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type SetCardOnCustomerRequest struct {
	CustomerId int32 `protobuf:"varint,1,opt,name=customerId" json:"customerId,omitempty"`
	Card       *Card `protobuf:"bytes,2,opt,name=card" json:"card,omitempty"`
}

func (m *SetCardOnCustomerRequest) Reset()                    { *m = SetCardOnCustomerRequest{} }
func (m *SetCardOnCustomerRequest) String() string            { return proto.CompactTextString(m) }
func (*SetCardOnCustomerRequest) ProtoMessage()               {}
func (*SetCardOnCustomerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *SetCardOnCustomerRequest) GetCustomerId() int32 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

func (m *SetCardOnCustomerRequest) GetCard() *Card {
	if m != nil {
		return m.Card
	}
	return nil
}

type SetCardOnCustomerResponse struct {
	Customer *Customer `protobuf:"bytes,1,opt,name=customer" json:"customer,omitempty"`
}

func (m *SetCardOnCustomerResponse) Reset()                    { *m = SetCardOnCustomerResponse{} }
func (m *SetCardOnCustomerResponse) String() string            { return proto.CompactTextString(m) }
func (*SetCardOnCustomerResponse) ProtoMessage()               {}
func (*SetCardOnCustomerResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

func (m *SetCardOnCustomerResponse) GetCustomer() *Customer {
	if m != nil {
		return m.Customer
	}
	return nil
}

func init() {
	proto.RegisterType((*ErrorResponse)(nil), "protobufs.ErrorResponse")
	proto.RegisterType((*Company)(nil), "protobufs.Company")
	proto.RegisterType((*CreateSessionRequest)(nil), "protobufs.CreateSessionRequest")
	proto.RegisterType((*CreateSessionResponse)(nil), "protobufs.CreateSessionResponse")
	proto.RegisterType((*CreateCompanyRequest)(nil), "protobufs.CreateCompanyRequest")
	proto.RegisterType((*CreateCompanyResponse)(nil), "protobufs.CreateCompanyResponse")
	proto.RegisterType((*SetCompanyImageLinkRequest)(nil), "protobufs.SetCompanyImageLinkRequest")
	proto.RegisterType((*SetCompanyImageLinkResponse)(nil), "protobufs.SetCompanyImageLinkResponse")
	proto.RegisterType((*SetCompanyPasswordRequest)(nil), "protobufs.SetCompanyPasswordRequest")
	proto.RegisterType((*SetCompanyPasswordResponse)(nil), "protobufs.SetCompanyPasswordResponse")
	proto.RegisterType((*Studio)(nil), "protobufs.Studio")
	proto.RegisterType((*SelectStudiosResponse)(nil), "protobufs.SelectStudiosResponse")
	proto.RegisterType((*CreateStudioRequest)(nil), "protobufs.CreateStudioRequest")
	proto.RegisterType((*CreateStudioResponse)(nil), "protobufs.CreateStudioResponse")
	proto.RegisterType((*UpdateStudioRequest)(nil), "protobufs.UpdateStudioRequest")
	proto.RegisterType((*UpdateStudioResponse)(nil), "protobufs.UpdateStudioResponse")
	proto.RegisterType((*DeleteStudioRequest)(nil), "protobufs.DeleteStudioRequest")
	proto.RegisterType((*DeleteStudioResponse)(nil), "protobufs.DeleteStudioResponse")
	proto.RegisterType((*Staff)(nil), "protobufs.Staff")
	proto.RegisterType((*SelectStaffsResponse)(nil), "protobufs.SelectStaffsResponse")
	proto.RegisterType((*CreateStaffRequest)(nil), "protobufs.CreateStaffRequest")
	proto.RegisterType((*CreateStaffResponse)(nil), "protobufs.CreateStaffResponse")
	proto.RegisterType((*DeleteStaffRequest)(nil), "protobufs.DeleteStaffRequest")
	proto.RegisterType((*DeleteStaffResponse)(nil), "protobufs.DeleteStaffResponse")
	proto.RegisterType((*UpdateStaffRequest)(nil), "protobufs.UpdateStaffRequest")
	proto.RegisterType((*UpdateStaffResponse)(nil), "protobufs.UpdateStaffResponse")
	proto.RegisterType((*Card)(nil), "protobufs.Card")
	proto.RegisterType((*Customer)(nil), "protobufs.Customer")
	proto.RegisterType((*SelectCustomersResponse)(nil), "protobufs.SelectCustomersResponse")
	proto.RegisterType((*CreateCustomerRequest)(nil), "protobufs.CreateCustomerRequest")
	proto.RegisterType((*CreateCustomerResponse)(nil), "protobufs.CreateCustomerResponse")
	proto.RegisterType((*DeleteCustomerRequest)(nil), "protobufs.DeleteCustomerRequest")
	proto.RegisterType((*DeleteCustomerResponse)(nil), "protobufs.DeleteCustomerResponse")
	proto.RegisterType((*SetCardOnCustomerRequest)(nil), "protobufs.SetCardOnCustomerRequest")
	proto.RegisterType((*SetCardOnCustomerResponse)(nil), "protobufs.SetCardOnCustomerResponse")
	proto.RegisterEnum("protobufs.ErrorType", ErrorType_name, ErrorType_value)
}

func init() { proto.RegisterFile("all.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 925 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0x5d, 0x6f, 0xe3, 0x44,
	0x14, 0xc5, 0xce, 0xa7, 0x6f, 0xb6, 0x8b, 0x77, 0x9a, 0x16, 0xb7, 0x20, 0x14, 0x0d, 0x5f, 0xe1,
	0x43, 0x5d, 0x08, 0x0f, 0x48, 0x88, 0x95, 0xd6, 0x24, 0xae, 0x64, 0x08, 0xc9, 0x32, 0x4e, 0x0b,
	0x3c, 0xa0, 0xc8, 0xb5, 0x27, 0xc5, 0x34, 0xb1, 0x83, 0xc7, 0x11, 0xda, 0x67, 0x9e, 0x79, 0xe6,
	0x0f, 0xf0, 0x43, 0x57, 0xb6, 0x67, 0x6c, 0xc7, 0x4d, 0xbd, 0xd9, 0x3c, 0xb5, 0x73, 0xef, 0x9d,
	0x7b, 0xcf, 0x39, 0xf7, 0x4c, 0x12, 0x50, 0xec, 0xe5, 0xf2, 0x62, 0x1d, 0x06, 0x51, 0x80, 0x94,
	0xe4, 0xcf, 0xcd, 0x66, 0xc1, 0xf0, 0xef, 0x70, 0x64, 0x84, 0x61, 0x10, 0x12, 0xca, 0xd6, 0x81,
	0xcf, 0x28, 0x1a, 0x80, 0x42, 0xe3, 0xc0, 0xec, 0xe5, 0x9a, 0x6a, 0x52, 0x4f, 0xea, 0x3f, 0x1e,
	0x74, 0x2f, 0xb2, 0xfa, 0x0b, 0x43, 0xe4, 0x48, 0x5e, 0x86, 0x34, 0x68, 0xad, 0x28, 0x63, 0xf6,
	0x2d, 0xd5, 0xe4, 0x9e, 0xd4, 0x57, 0x88, 0x38, 0xe2, 0x7f, 0x25, 0x68, 0x0d, 0x83, 0xd5, 0xda,
	0xf6, 0x5f, 0xa2, 0xc7, 0x20, 0x7b, 0x6e, 0xd2, 0xb2, 0x41, 0x64, 0xcf, 0x45, 0x08, 0xea, 0xbe,
	0xbd, 0x12, 0x57, 0x92, 0xff, 0x11, 0x86, 0x47, 0x74, 0x65, 0x7b, 0x4b, 0xdd, 0x75, 0x43, 0xca,
	0x98, 0x56, 0x4b, 0x72, 0x5b, 0x31, 0xf4, 0x1e, 0x28, 0x4e, 0x48, 0xed, 0x88, 0xba, 0x7a, 0xa4,
	0xd5, 0x7b, 0x52, 0xbf, 0x46, 0xf2, 0x40, 0x9c, 0xf5, 0x56, 0xf6, 0x2d, 0x1d, 0x9b, 0xfe, 0x9d,
	0xd6, 0x48, 0xae, 0xe7, 0x01, 0x7c, 0x0d, 0xdd, 0x61, 0x52, 0x6a, 0x51, 0xc6, 0xbc, 0xc0, 0x27,
	0xf4, 0xaf, 0x0d, 0x65, 0xd1, 0xbd, 0xb9, 0xd2, 0x8e, 0xb9, 0xe7, 0xd0, 0x5e, 0xdb, 0x8c, 0xfd,
	0x1d, 0x84, 0x2e, 0xc7, 0x9c, 0x9d, 0xb1, 0x01, 0x27, 0xa5, 0xbe, 0x5c, 0xce, 0x2f, 0xa0, 0xe5,
	0xa4, 0xfc, 0x93, 0x9e, 0x9d, 0x01, 0x2a, 0x88, 0xc9, 0x95, 0x21, 0xa2, 0x04, 0xff, 0x29, 0xe0,
	0x89, 0x0c, 0x87, 0x27, 0xa4, 0x92, 0x2a, 0xa4, 0x92, 0x5f, 0x03, 0xb9, 0xf6, 0x10, 0xe4, 0x6c,
	0xd6, 0x41, 0x90, 0xbf, 0x85, 0x73, 0x8b, 0x46, 0x3c, 0x6c, 0x26, 0x42, 0x7b, 0xfe, 0x9d, 0x00,
	0x9e, 0x6d, 0xc3, 0xf3, 0xef, 0x38, 0xfa, 0x3c, 0x80, 0x7f, 0x84, 0x77, 0x77, 0xde, 0x3d, 0x08,
	0xc8, 0x37, 0x70, 0x96, 0x37, 0x7b, 0xc1, 0x59, 0x0a, 0x1c, 0x45, 0x21, 0xa4, 0x92, 0x10, 0x3f,
	0x14, 0x19, 0xe4, 0x17, 0x0f, 0x02, 0xf1, 0xbf, 0x04, 0x4d, 0x2b, 0xda, 0xb8, 0x5e, 0xb0, 0x97,
	0xdd, 0x35, 0x68, 0xd9, 0x5b, 0x4e, 0x17, 0x47, 0xd4, 0x83, 0xce, 0xfa, 0x8f, 0xc0, 0xa7, 0x93,
	0xcd, 0xea, 0x86, 0x86, 0x89, 0xcd, 0x15, 0x52, 0x0c, 0x6d, 0x3f, 0x83, 0xc6, 0x83, 0xcf, 0x20,
	0x16, 0xbe, 0x59, 0x16, 0x7e, 0x04, 0x27, 0x16, 0x5d, 0x52, 0x27, 0x4a, 0xb1, 0xb2, 0x8c, 0xed,
	0xe7, 0xd0, 0x62, 0x69, 0x48, 0x93, 0x7a, 0xb5, 0x7e, 0x67, 0xf0, 0xa4, 0xc0, 0x36, 0x2d, 0x26,
	0xa2, 0x02, 0xff, 0x23, 0xc1, 0x31, 0x77, 0x7d, 0x9a, 0xa9, 0x70, 0x6b, 0x81, 0xa9, 0x5c, 0xc9,
	0xb4, 0xb6, 0x93, 0x69, 0xce, 0xa5, 0x5e, 0xe6, 0xa2, 0x67, 0x4f, 0x9a, 0x83, 0xe0, 0x54, 0x3e,
	0x85, 0x66, 0x0a, 0x94, 0xef, 0x6d, 0x07, 0x13, 0x5e, 0x80, 0x9f, 0xc3, 0xf1, 0xd5, 0xda, 0xbd,
	0xc7, 0xe3, 0x0d, 0x3a, 0xe8, 0xd0, 0xdd, 0xee, 0xf0, 0xe6, 0x20, 0x3e, 0x82, 0xe3, 0x11, 0x5d,
	0xd2, 0x32, 0x88, 0x92, 0x8d, 0xf0, 0x97, 0xd0, 0xdd, 0x2e, 0xe3, 0x93, 0x34, 0x68, 0xb1, 0x8d,
	0xe3, 0x88, 0x0f, 0xaf, 0x36, 0x11, 0x47, 0x7c, 0x0b, 0x0d, 0x2b, 0xb2, 0x17, 0x8b, 0xbd, 0x1c,
	0xb9, 0xe5, 0xaa, 0x5a, 0xa5, 0xab, 0xee, 0x6d, 0xe2, 0x39, 0x74, 0x85, 0xab, 0xec, 0xc5, 0x22,
	0x37, 0x55, 0x3f, 0x16, 0x21, 0x8e, 0x70, 0x4f, 0xa9, 0x5b, 0x22, 0xd8, 0x8b, 0x05, 0xe1, 0x79,
	0x7c, 0x09, 0x48, 0xec, 0x32, 0x0e, 0x57, 0xf8, 0x69, 0x0b, 0x89, 0x5c, 0x46, 0xf2, 0x2c, 0x37,
	0x66, 0xd2, 0x87, 0x03, 0xf9, 0x18, 0x1a, 0xc9, 0x20, 0xbe, 0x8c, 0xfb, 0x38, 0xd2, 0x34, 0xfe,
	0x10, 0x90, 0xd0, 0xb8, 0x00, 0xa3, 0xbc, 0x89, 0xa7, 0xf9, 0xc2, 0x8a, 0x43, 0x1e, 0x5e, 0xc4,
	0x77, 0x80, 0x84, 0x49, 0x0a, 0x6d, 0xf7, 0x05, 0xf5, 0x2c, 0x37, 0xe9, 0x21, 0x9c, 0x2e, 0xa0,
	0x3e, 0xb4, 0x43, 0xb7, 0xc0, 0x42, 0x49, 0x4c, 0x70, 0x0a, 0x4d, 0x27, 0xa4, 0xae, 0x17, 0x25,
	0x2a, 0x36, 0x08, 0x3f, 0xe1, 0x0d, 0xb4, 0x87, 0x1b, 0x16, 0x05, 0x2b, 0x1a, 0xee, 0x65, 0x9c,
	0x1e, 0x74, 0x5c, 0xca, 0x9c, 0xd0, 0x5b, 0x47, 0x5e, 0xe0, 0x8b, 0x67, 0x5c, 0x08, 0xa1, 0x0f,
	0xa0, 0xee, 0xd8, 0xa1, 0x9b, 0xf8, 0xa6, 0x33, 0x78, 0xbb, 0xf8, 0x31, 0x6a, 0x87, 0x2e, 0x49,
	0x92, 0x78, 0x0c, 0xef, 0xa4, 0x1e, 0x12, 0xc3, 0x73, 0x1b, 0x7d, 0x05, 0x8a, 0x23, 0x82, 0xdc,
	0x49, 0xc7, 0xc5, 0x26, 0x3c, 0x47, 0xf2, 0x2a, 0x1c, 0x66, 0xdf, 0x71, 0x22, 0x59, 0x61, 0xa9,
	0x12, 0x03, 0xf9, 0x61, 0x06, 0xb5, 0x2a, 0x06, 0x26, 0x9c, 0x96, 0x67, 0x72, 0x02, 0x4f, 0xa1,
	0x2d, 0xa0, 0xf1, 0x6d, 0xed, 0xc4, 0x9f, 0x15, 0xe1, 0x4f, 0xe0, 0x24, 0x75, 0x58, 0x19, 0x7e,
	0xd9, 0x8a, 0x03, 0x38, 0x2d, 0x17, 0xbe, 0xd6, 0x8d, 0x73, 0xd0, 0xe2, 0xaf, 0x3d, 0x3b, 0x74,
	0xa7, 0x7e, 0xb9, 0xff, 0xfb, 0x00, 0x02, 0x84, 0x29, 0xe6, 0x14, 0x22, 0x99, 0x10, 0x72, 0xf5,
	0x2a, 0xcf, 0x76, 0x0c, 0x38, 0x50, 0x8b, 0xcf, 0xfe, 0x93, 0x40, 0xc9, 0x7e, 0x7c, 0xa2, 0x73,
	0x38, 0x35, 0x27, 0xd7, 0xfa, 0xd8, 0x1c, 0xcd, 0x89, 0xf1, 0xf3, 0x95, 0x61, 0xcd, 0xe6, 0x97,
	0x53, 0xf2, 0x93, 0x3e, 0x53, 0xdf, 0x42, 0x47, 0xa0, 0x4c, 0xa6, 0xf1, 0xf9, 0x6a, 0x32, 0x52,
	0x25, 0xf4, 0x04, 0x8e, 0xf4, 0x31, 0x31, 0xf4, 0xd1, 0x6f, 0x73, 0xe3, 0x57, 0xd3, 0x9a, 0xa9,
	0x32, 0xea, 0x82, 0x2a, 0x6e, 0xbf, 0xd0, 0x2d, 0xeb, 0x97, 0x29, 0x19, 0xa9, 0x35, 0x74, 0x06,
	0x27, 0xe6, 0x64, 0x66, 0x90, 0x89, 0x3e, 0x9e, 0x5b, 0x06, 0xb9, 0x36, 0xc8, 0xdc, 0x20, 0x64,
	0x4a, 0xd4, 0x7a, 0xdc, 0xf2, 0x72, 0x4a, 0xbe, 0x37, 0x47, 0x23, 0x63, 0xa2, 0x36, 0xd0, 0x23,
	0x68, 0x0f, 0xa7, 0x93, 0xcb, 0xb1, 0x39, 0x9c, 0xa9, 0xcd, 0x9b, 0x66, 0x82, 0xfb, 0xeb, 0x57,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xcb, 0x30, 0x5e, 0x02, 0x61, 0x0b, 0x00, 0x00,
}
