// Code generated by protoc-gen-go. DO NOT EDIT.
// source: create-session.proto

/*
Package protobufs is a generated protocol buffer package.

It is generated from these files:
	create-session.proto

It has these top-level messages:
	CreateSessionRequest
	CreateSessionResponse
*/
package protobufs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateSessionRequest struct {
	EmailAddress string `protobuf:"bytes,1,opt,name=emailAddress" json:"emailAddress,omitempty"`
	Password     string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *CreateSessionRequest) Reset()                    { *m = CreateSessionRequest{} }
func (m *CreateSessionRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateSessionRequest) ProtoMessage()               {}
func (*CreateSessionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateSessionRequest) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *CreateSessionRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateSessionResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *CreateSessionResponse) Reset()                    { *m = CreateSessionResponse{} }
func (m *CreateSessionResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateSessionResponse) ProtoMessage()               {}
func (*CreateSessionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateSessionResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*CreateSessionRequest)(nil), "protobufs.CreateSessionRequest")
	proto.RegisterType((*CreateSessionResponse)(nil), "protobufs.CreateSessionResponse")
}

func init() { proto.RegisterFile("create-session.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 145 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x49, 0x2e, 0x4a, 0x4d,
	0x2c, 0x49, 0xd5, 0x2d, 0x4e, 0x2d, 0x2e, 0xce, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0xe2, 0x04, 0x53, 0x49, 0xa5, 0x69, 0xc5, 0x4a, 0x61, 0x5c, 0x22, 0xce, 0x60, 0x25, 0xc1,
	0x10, 0x15, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x4a, 0x5c, 0x3c, 0xa9, 0xb9, 0x89,
	0x99, 0x39, 0x8e, 0x29, 0x29, 0x45, 0xa9, 0xc5, 0xc5, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41,
	0x28, 0x62, 0x42, 0x52, 0x5c, 0x1c, 0x05, 0x89, 0xc5, 0xc5, 0xe5, 0xf9, 0x45, 0x29, 0x12, 0x4c,
	0x60, 0x79, 0x38, 0x5f, 0xc9, 0x90, 0x4b, 0x14, 0xcd, 0xdc, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54,
	0x21, 0x09, 0x2e, 0xf6, 0xe2, 0xd2, 0xe4, 0x64, 0x98, 0x99, 0x1c, 0x41, 0x30, 0x6e, 0x12, 0x1b,
	0xd8, 0x55, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x53, 0x16, 0xf6, 0x1e, 0xb4, 0x00, 0x00,
	0x00,
}
